fix galaxy provisioning

diff --git a/galaxy/config/etc/init.d/galaxy b/galaxy/config/etc/init.d/galaxy
--- a/galaxy/config/etc/init.d/galaxy
+++ b/galaxy/config/etc/init.d/galaxy
@@ -1,52 +1,105 @@
 #!/bin/bash
+#
+# Init file for Galaxy (http://galaxyproject.org/)
+#   Suitable for use on Fedora and derivatives (RedHat Enterprise Linux, Scientific Linux, CentOS)
+#
+# Contributed by Brad Chapman
+#
+# chkconfig: 2345 98 20
+# description: Galaxy http://galaxyproject.org/
 
-# Author: James Casbon, 2009
+#--- config
 
-### BEGIN INIT INFO
-# Provides:             galaxy
-# Required-Start:       $network $local_fs $postgresql
-# Required-Stop:
-# Default-Start:        2 3 4 5
-# Default-Stop:         0 1 6
-# Short-Description:    Galaxy
-### END INIT INFO
+SERVICE_NAME="galaxy"
+RUN_AS="vagrant"
+RUN_IN="/home/vagrant/galaxy-dist"
 
-. /lib/lsb/init-functions
+#--- main actions
 
-USER="vagrant"
-GROUP="vagrant"
-DIR="/home/vagrant/galaxy-dist/"
-PYTHON="/usr/bin/python"
-OPTS="./scripts/paster.py serve --log-file /home/${USER}/galaxy.log config/galaxy.ini"
-PIDFILE="/var/run/galaxy.pid"
+start() {
+    echo "Starting $SERVICE_NAME... "
+    cmd="cd $RUN_IN && sh run.sh --daemon"
+    case "$(id -un)" in
+        $RUN_AS)
+            eval "$cmd"
+            ;;
+        root)
+            su - $RUN_AS -c "$cmd"
+            ;;
+        *)
+            echo "*** ERROR *** must be $RUN_AS or root in order to control this service" >&2
+            exit 1
+    esac
+    echo "...done."
+}
 
-case "${1:-''}" in
-  'start')
-           log_daemon_msg "Starting Galaxy"
-           if start-stop-daemon --chuid $USER --group $GROUP --start --make-pidfile \
-                 --pidfile $PIDFILE --background --chdir $DIR --exec $PYTHON -- $OPTS; then
-             log_end_msg 0
-           else
-             log_end_msg 1
-       fi
+stop() {
+    echo -n "Stopping $SERVICE_NAME... "
 
+    cmd="cd $RUN_IN && sh run.sh --stop-daemon"
+
+    case "$(id -un)" in
+        $RUN_AS)
+            eval "$cmd"
+            ;;
+        root)
+            su - $RUN_AS -c "$cmd"
+            ;;
+        *)
+            echo "*** ERROR *** must be $RUN_AS or root in order to control this service" >&2
+            exit 1
+    esac
+
+    echo "done."
+}
+
+status() {
+    echo -n "$SERVICE_NAME status: "
+
+    while read pid; do
+        if [ "$(readlink -m /proc/$pid/cwd)" = "$(readlink -m $RUN_IN)" ]; then
+            echo "started"
+            return 0
+        fi
+    done < <(ps ax -o 'pid cmd' | grep -P '^\s*\d+ python ./scripts/paster.py serve' | awk '{print $1}')
+    echo "stopped"
+    return 3
+}
+
+notsupported() {
+    echo "*** ERROR*** $SERVICE_NAME: operation [$1] not supported"
+}
+
+usage() {
+    echo "Usage: $SERVICE_NAME start|stop|restart|status"
+}
+
+
+#---
+
+case "$1" in
+    start)
+        start "$@"
         ;;
-  'stop')
-           log_daemon_msg "Stopping Galaxy"
-       if start-stop-daemon --stop --pidfile $PIDFILE; then
-         log_end_msg 0
-       else
-         log_end_msg 1
-       fi
+    stop)
+        stop
         ;;
-  'restart')
-           # restart commands here
-       $0 stop
-       $0 start
-
+    restart|reload)
+        stop
+        start
         ;;
-  *)      # no parameter specified
-        echo "Usage: $SELF start|stop|restart|reload|force-reload|status"
+    status)
+        set +e
+        status
+        exit $?
+        ;;
+    '')
+        usage >&2
+        exit 1
+        ;;
+    *)
+        notsupported "$1" >&2
+        usage >&2
         exit 1
         ;;
 esac
